[2024-12-07 11:20:11] [WARNING] discord.client: PyNaCl is not installed, voice will NOT be supported
[2024-12-07 11:20:11] [INFO   ] discord.client: logging in using static token
[2024-12-07 11:20:12] [INFO   ] discord.gateway: Shard ID None has connected to Gateway (Session ID: baf809b02e83089f47b33854ee9affe7).
[2024-12-07 11:20:14] [INFO   ] racbot: Ready: RAC#8732 (ID: 1221491594516103188)
[2024-12-07 11:20:29] [WARNING] discord.client: PyNaCl is not installed, voice will NOT be supported
[2024-12-07 11:20:29] [INFO   ] discord.client: logging in using static token
[2024-12-07 11:20:29] [ERROR  ] racbot: failed to load extension cogs.owner
Traceback (most recent call last):
  File "C:\Repositories\RAC-Bot\venv\Lib\site-packages\discord\ext\commands\bot.py", line 951, in _load_from_module_spec
    spec.loader.exec_module(lib)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "c:\Repositories\RAC-Bot\src\bot\cogs\owner.py", line 13, in <module>
    from ..racbot import RACBot
ImportError: attempted relative import beyond top-level package

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Repositories\RAC-Bot\src\bot\racbot.py", line 104, in setup_hook
    await self.load_extension(extension)
  File "C:\Repositories\RAC-Bot\venv\Lib\site-packages\discord\ext\commands\bot.py", line 1029, in load_extension
    await self._load_from_module_spec(spec, name)
  File "C:\Repositories\RAC-Bot\venv\Lib\site-packages\discord\ext\commands\bot.py", line 954, in _load_from_module_spec
    raise errors.ExtensionFailed(key, e) from e
discord.ext.commands.errors.ExtensionFailed: Extension 'cogs.owner' raised an error: ImportError: attempted relative import beyond top-level package
[2024-12-07 11:20:30] [INFO   ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 5f960616165d6920e0549c48f35488be).
[2024-12-07 11:20:32] [INFO   ] racbot: Ready: RAC#8732 (ID: 1221491594516103188)
[2024-12-07 11:20:43] [WARNING] discord.client: PyNaCl is not installed, voice will NOT be supported
[2024-12-07 11:20:43] [INFO   ] discord.client: logging in using static token
[2024-12-07 11:20:44] [INFO   ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 56031a97570ac10c077b38aeafdab132).
[2024-12-07 11:20:46] [INFO   ] racbot: Ready: RAC#8732 (ID: 1221491594516103188)
[2024-12-07 12:21:16] [WARNING] discord.client: PyNaCl is not installed, voice will NOT be supported
[2024-12-07 12:21:16] [INFO   ] discord.client: logging in using static token
[2024-12-07 12:21:17] [INFO   ] discord.gateway: Shard ID None has connected to Gateway (Session ID: d2355abb91d3f13b517ce018de48e60b).
[2024-12-07 12:21:19] [INFO   ] racbot: Ready: RAC#8732 (ID: 1221491594516103188)
[2024-12-07 12:24:49] [WARNING] discord.client: PyNaCl is not installed, voice will NOT be supported
[2024-12-07 12:24:49] [INFO   ] discord.client: logging in using static token
[2024-12-07 12:24:50] [INFO   ] discord.gateway: Shard ID None has connected to Gateway (Session ID: c174d0b701591b8c386aad91671b8b86).
[2024-12-07 12:24:52] [INFO   ] racbot: Ready: RAC#8732 (ID: 1221491594516103188)
[2024-12-07 12:39:31] [ERROR  ] racbot: In uploadcommands:
Traceback (most recent call last):
  File "C:\Repositories\RAC-Bot\venv\Lib\site-packages\discord\ext\commands\core.py", line 235, in wrapped
    ret = await coro(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Repositories\RAC-Bot\src\bot\cogs\owner.py", line 209, in uploadcommands
    js.update(
ValueError: dictionary update sequence element #0 has length 1; 2 is required
